spring:
  datasource:
    url: jdbc:postgresql://${TWITTER_DB_HOST}:${TWITTER_DB_PORT}/${TWITTER_DB_NAME}
    username: ${TWITTER_DB_USERNAME}
    password: ${TWITTER_DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
logging:
  level:
    org:
      springframework:
        security: debug