services:
  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${TWITTER_DB_USERNAME}
      - POSTGRES_PASSWORD=${TWITTER_DB_PASSWORD}
      - POSTGRES_DB=${TWITTER_DB_NAME}
    ports:
      - '${TWITTER_DB_PORT}:5432'
  sonar:
    image: sonarqube:26.8.0.126808-community
    ports:
      - '9000:9000'
